In [1]:
import pandas as pd
import numpy as np
import torch 

x=torch.tensor(3.0)
y=torch.tensor(2.0)
x+y,x-y,x/y,x*y,x**y

(tensor(5.), tensor(1.), tensor(1.5000), tensor(6.), tensor(9.))

In [2]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
len(x)

4

In [4]:
x.shape

torch.Size([4])

In [5]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [6]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [10]:
X=torch.arange(24,dtype=torch.float32).reshape(2,3,4)
X

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [12]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [13]:
a=2
a+A,(a*A).shape

(tensor([[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.]]),
 torch.Size([5, 4]))

In [6]:
X=torch.arange(24,dtype=torch.float32).reshape(2,3,4)#按照顺序来，axis=0：纵轴，axis=1:轴数为3的轴，axis=2:轴数为4的轴
X,X.sum(),X.sum(dim=0),X.sum(axis=1),X.sum(dim=2)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor(276.),
 tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 tensor([[ 6., 22., 38.],
         [54., 70., 86.]]))

In [22]:
X.mean(),X.sum()/X.numel()

(tensor(11.5000), tensor(11.5000))

In [8]:
X.mean(axis=0),X.sum(axis=0)/X.numel(dim=0)

TypeError: numel() takes no keyword arguments

In [28]:
X.mean(axis=0),X.sum(axis=0)/X.shape[0],X.shape[0],type(X.shape[0])

(tensor([[ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.]]),
 tensor([[ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.]]),
 2,
 int)

In [30]:
sum_X=X.sum(axis=0,keepdims=True)#保持轴数不变
sum_X

tensor([[[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]])

In [31]:
X/sum_X#可以直接处理

tensor([[[0.0000, 0.0714, 0.1250, 0.1667],
         [0.2000, 0.2273, 0.2500, 0.2692],
         [0.2857, 0.3000, 0.3125, 0.3235]],

        [[1.0000, 0.9286, 0.8750, 0.8333],
         [0.8000, 0.7727, 0.7500, 0.7308],
         [0.7143, 0.7000, 0.6875, 0.6765]]])

In [10]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
A,A.cumsum(axis=0)#cumsum保持维度不变

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

In [46]:
y=torch.ones(4,dtype=torch.float32)
x=torch.arange(4,dtype=torch.float32)
x*y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor(6.))

In [48]:
torch.sum(x*y)

tensor(6.)

In [50]:
A.shape,x.shape,torch.mv(A,x)#矩阵向量积

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [51]:
B=torch.ones(4,3)
torch.mm(A,B)#矩阵-矩阵积

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [54]:
#范数
u=torch.tensor([3.0,4.0])
torch.norm(u)#2范数

tensor(5.)

In [55]:
torch.abs(u).sum()#1范数

tensor(7.)

In [58]:
z=torch.ones(4,9)#ju'zhen
torch.norm(z)

tensor(6.)