#### 练习：线性回归模型

In [1]:
%matplotlib inline
import torch 
import random
import pandas as pd
import numpy as np
from d2l import torch as d2l
from torch.utils import data

In [2]:
true_w=torch.tensor([2,3.4])
true_b=4.2
num_samples=10000

In [3]:
def synthetic_data(num_sample,w,b):#生成数据集
    x=torch.normal(0,1,(num_sample,len(w)))
    y=torch.matmul(x,w)+b
    y+=torch.normal(0,0.1,y.shape)
    return x,y.reshape(-1,1)

In [4]:
features,labels=synthetic_data(num_samples,true_w,true_b)
features,labels

(tensor([[ 0.9122, -0.0373],
         [ 2.2978, -2.1508],
         [-0.9606,  0.3863],
         ...,
         [-2.3320,  1.6519],
         [-0.8149, -0.8024],
         [ 1.2429,  0.5432]]),
 tensor([[ 5.9714],
         [ 1.6470],
         [ 3.5018],
         ...,
         [ 5.1481],
         [-0.2107],
         [ 8.5707]]))

In [5]:
def data_loader(batch_size,num_sample,feature,label):#生成小批量数据
    indice=list(range(num_sample))
    random.shuffle(indice)
    for i in range(0,num_sample,batch_size):
        dataset=torch.tensor(indice[i:min(i+batch_size,num_sample)])
        yield feature[dataset],label[dataset]

In [6]:
batch_size=100
for x,y in data_loader(batch_size,num_samples,features,labels):
    print(x,'\n',y)
    break

tensor([[ 1.4245, -1.2619],
        [ 0.7763,  0.1446],
        [ 1.1326,  0.2849],
        [ 1.5852, -0.3670],
        [ 2.0391,  0.8342],
        [-1.1895, -0.6979],
        [ 0.1004, -0.7390],
        [ 0.8270, -0.8173],
        [ 1.6950, -1.9789],
        [-0.5066, -1.2859],
        [ 0.1925,  0.5155],
        [-0.9695, -1.4032],
        [-1.8424,  2.8958],
        [ 1.0681, -0.1511],
        [ 2.0831,  0.6630],
        [ 1.1927, -0.2640],
        [ 0.0397, -1.3921],
        [-0.1760,  0.6860],
        [ 0.3630, -0.2682],
        [-1.7781,  0.7089],
        [ 0.4594,  0.1544],
        [-0.2740, -0.0766],
        [ 0.8797,  1.2403],
        [-0.1596,  1.7460],
        [ 1.3496,  0.4286],
        [ 0.2633, -0.2059],
        [ 0.6629,  1.6410],
        [ 1.7032, -0.6139],
        [-0.4636, -0.9557],
        [ 0.1282, -0.4233],
        [-0.2951,  0.2461],
        [-0.0090, -0.2610],
        [ 0.3905, -0.8064],
        [-1.2821, -0.0549],
        [-1.0851, -0.2062],
        [-0.0450, -1

In [7]:
def linear(x,w,b):
    return torch.matmul(x,w)+b
def loss(y,y_hat):
    return (y_hat-y.reshape(y_hat.shape))**2/2
def sgd(batch_size,lr,params):
    with torch.no_grad():
        for param in params:
            param-=lr*param.grad/batch_size
            param.grad.zero_()

In [8]:
"""初始化"""
w=torch.normal(0,0.5,size=(2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

In [9]:
"""训练"""
num_epoch=
lr=0.01
for epoch in range(num_epoch):
    for x,y in data_loader(batch_size,num_samples,features,labels):
        y_hat=linear(x,w,b)
        l=loss(y,y_hat)
        l.sum().backward()
        sgd(batch_size,lr,[w,b])
    with torch.no_grad():
        train_loss=loss(labels,linear(features,w,b))
        print(f'epoch={epoch+1},loss={float(train_loss.mean()):.5f}')

epoch=1,loss=2.33414
epoch=2,loss=0.32784
epoch=3,loss=0.04971
epoch=4,loss=0.01117
epoch=5,loss=0.00582
