In [2]:
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
def pooling(x,kernel_size,mode='maxn'):
    h,w=kernel_size
    y=torch.zeros((x.shape[0]-h+1,x.shape[1]-w+1))#步长默认为1
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            if mode=='maxn':
                y[i][j]=x[i:i+h,j:j+w].max()
            if mode=='avg':
                y[i][j]=x[i:i+h,j:j+w].mean()
    return y

In [5]:
x=torch.tensor([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])
pooling(x,(2,2))

tensor([[4., 5.],
        [7., 8.]])

In [6]:
pooling(x,(2,2),'avg')

tensor([[2., 3.],
        [5., 6.]])

In [9]:
X=torch.arange(16,dtype=torch.float32).reshape((1,1,4,4))
#默认情况下，深度学习中pooling层步长和窗口大小相同
pool2d=nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10., 11.],
          [14., 15.]]]])

In [10]:
#也可以自己手动设置padding和stride
pool2d=nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [11]:
pool2d=nn.MaxPool2d((2,3),stride=(2,3),padding=(0,1))
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [12]:
x=torch.cat((X,X+1),1)#按照第一维进行堆叠（1，1，4，4）->(1,2,4,4)
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [13]:
pool2d=nn.MaxPool2d(3,stride=2,padding=1)
pool2d(x)#输出通道数目不变

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])